# services:
#   frontend:
#           build: phase_3/.
#           ports: 
#           - "4500:4500"
#   backend:
#           build: formated-backend/.
#           ports: 
#           - "3000:3000"
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
